StokOtomasyanu/Controllers/KisiZimmetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StokOtomasyanu;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;

namespace StokOtomasyanu.Controllers
{
    public class KisiZimmetController : Controller
    {
        private StokTakipContext db = new StokTakipContext();

       
        public ActionResult Index()
        {
            
            var kisiZimmets = db.KisiZimmets.Include(k => k.Kullanicilar).Include(k => k.Urunler);
            
            return View(kisiZimmets.ToList());
        }



        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni()
        {
            ViewBag.KisiId = new SelectList(db.Kullanicilars, "KullaniciId", "KullaniciAdi");
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi");
            return View();
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni([Bind(Include = "KisiZimmetId,KisiId,UrunId,Durum")] KisiZimmet kisiZimmet)
        {
            if (ModelState.IsValid)
            {
               
                var kisizimmet1=db.KisiZimmets.FirstOrDefault(x=>x.UrunId==kisiZimmet.UrunId && x.UrunId==kisiZimmet.UrunId);
                if (kisizimmet1==null)
                {
                    db.KisiZimmets.Add(kisiZimmet);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Bu ürün daha önce zimmetlendi.";
                }

            }

            ViewBag.KisiId = new SelectList(db.Kullanicilars, "KullaniciId", "KullaniciAdi", kisiZimmet.KisiId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", kisiZimmet.UrunId);
            return View(kisiZimmet);
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KisiZimmet kisiZimmet = db.KisiZimmets.Find(id);
            if (kisiZimmet == null)
            {
                return HttpNotFound();
            }
            ViewBag.KisiId = new SelectList(db.Kullanicilars, "KullaniciId", "KullaniciAdi", kisiZimmet.KisiId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", kisiZimmet.UrunId);
            return View(kisiZimmet);
        }
        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle([Bind(Include = "KisiZimmetId,KisiId,UrunId,Durum")] KisiZimmet kisiZimmet)
        {
            if (ModelState.IsValid)
            {
             


                db.Entry(kisiZimmet).State = EntityState.Modified;
                    
                    db.SaveChanges();
                    return RedirectToAction("Index");
             

                
                
            }
            ViewBag.KisiId = new SelectList(db.Kullanicilars, "KullaniciId", "KullaniciAdi", kisiZimmet.KisiId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", kisiZimmet.UrunId);
            return View(kisiZimmet);
        }
        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        public string Sil(int id)
        {
            KisiZimmet kisi = db.KisiZimmets.FirstOrDefault(x => x.KisiZimmetId == id);
            db.KisiZimmets.Remove(kisi);
            try
            {
                db.SaveChanges();
                return "başarılı";
            }
            catch (Exception e)
            {
                return "hata";
            }


        }


        [HttpPost]
        [ValidateInput(false)]
        public FileResult Pdf(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 50f, 10f, 50f, 20f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "KisiZimmetRapor.pdf");
            }
        }


       
    }
}

StokOtomasyanu/Views/KisiZimmet/Duzenle.cshtml
@model StokOtomasyanu.KisiZimmet

@{
    ViewBag.Title = "Düzenle";
}

<h2>Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Kişi Zimmet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p class="text-danger"> @ViewBag.Yanlis</p>
    @Html.HiddenFor(model => model.KisiZimmetId)

    <div class="form-group">
        @Html.LabelFor(model => model.KisiId, "Kişi Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KisiId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KisiId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunId, "Ürün Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UrunId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UrunId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

StokOtomasyanu/Views/KisiZimmet/Index.cshtml
@model IEnumerable<StokOtomasyanu.KisiZimmet>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
@if (User.IsInRole("Admin") || User.IsInRole("Satın Alma Şefi"))
{
    @Html.ActionLink("Yeni", "Yeni", "", htmlAttributes: new {@class = "btn btn-success"})
}
</p>
<div id="Grid">
    <table class="table">
        <tr>
            <th>
                Durum
            </th>
            <th>
                Kullanıcı Adı
            </th>
            <th>
                Ürün Adı
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @if (item.Durum == true)
                    {
                        @Html.Label("Aktif")

                    }
                    else
                    {
                        @Html.Label("Pasif")
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kullanicilar.KullaniciAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Urunler.UrunaAdi)
                </td>
                <td>
                @if (User.IsInRole("Admin") || User.IsInRole("Satın Alma Şefi"))
                {
                    @Html.ActionLink("Düzenle", "Duzenle", new {id = item.KisiZimmetId}, htmlAttributes: new {@class = "btn btn-warning"})

                    <a href="#" class="btn btn-danger kisizimsil" data-kisizimid="@item.KisiZimmetId">Sil</a>
                }
                </td>
            </tr>
        }

    </table>
</div>


    @using (Html.BeginForm("Pdf", "KisiZimmet", FormMethod.Post))
    {
        <input type="hidden" name="GridHtml" />
        <input class="btn btn-default" type="submit" id="btnSubmit" value="Rapor" />
    }
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#btnSubmit").click(function () {
                $("input[name='GridHtml']").val($("#Grid").html());
            });
        });
    </script>



    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>

        $(".kisizimsil").click(function () {
            var sonuc = confirm("Kayıt Silinsin mi?");
            if (sonuc) {
                var kisizimid = $(this).data("kisizimid");
                $.ajax({
                    type: "POST",
                    url: "/KisiZimmet/Sil/" + kisizimid,
                    success: function (parameters) {
                        alert("Kayıt Silindi");
                        window.location.replace("/KisiZimmet/Index");
                    },
                    error: function () {
                        alert("kayıt silme sırasında hata oluştu");
                    }



                });

            } else {
                alert("iptal edildi");

            }

        });
    </script>

StokOtomasyanu/Views/KisiZimmet/Yeni.cshtml
@model StokOtomasyanu.KisiZimmet

@{
    ViewBag.Title = "Yeni";
}

<h2>Yeni</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Kişi Zimmet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p class="text-danger"> @ViewBag.Yanlis</p>
    <div class="form-group">
        @Html.LabelFor(model => model.KisiId, "Kişi Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KisiId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KisiId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunId, "Ürün Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UrunId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UrunId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Oluştur" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>