StokOtomasyanu/Controllers/AtikController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using StokOtomasyanu;

namespace StokOtomasyanu.Controllers
{

    public class AtikController : Controller
    {
        private StokTakipContext db = new StokTakipContext();

        
        public ActionResult Index()
        {
            var atiklars = db.Atiklars.Include(a => a.Urunler);
            return View(atiklars.ToList());
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni()
        {
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi");
            return View();
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni([Bind(Include = "AtikId,UrunId")] Atiklar atiklar)
        {
            if (ModelState.IsValid)
            {
                var atik1 = db.Atiklars.FirstOrDefault(x => x.UrunId == atiklar.UrunId);
                if (atik1==null)
                {
                    db.Atiklars.Add(atiklar);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Aynı atıklara atılamaz. .";
                }
              
            }

            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", atiklar.UrunId);
            return View(atiklar);
        }
       
       

      

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        public string Sil(int id)
        {
            Atiklar atiklar = db.Atiklars.FirstOrDefault(x => x.AtikId == id);
            db.Atiklars.Remove(atiklar);
            try
            {
                db.SaveChanges();
                return "başarılı";
            }
            catch (Exception e)
            {
                return "hata";
            }


        }

        [HttpPost]
        [ValidateInput(false)]
        public FileResult Pdf(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 50f, 10f, 50f, 10f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "AtikRapor.pdf");
            }
        }

    }
}

StokOtomasyanu/Controllers/BolumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StokOtomasyanu;

namespace StokOtomasyanu.Controllers
{
   
    public class BolumController : Controller
    {
        private StokTakipContext db = new StokTakipContext();

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Index()
        {
            return View(db.Bolums.ToList());
        }



        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni([Bind(Include = "BolumId,BolumAdi")] Bolum bolum)
        {


            if (ModelState.IsValid)
            {
                var bolum1 = db.Bolums.FirstOrDefault(x => x.BolumAdi == bolum.BolumAdi);
                if (bolum1==null)
                {
                    db.Bolums.Add(bolum);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Bu Bölüm mevcut";
                }
                
            }

            return View(bolum);
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bolum bolum = db.Bolums.Find(id);
            if (bolum == null)
            {
                return HttpNotFound();
            }
            return View(bolum);
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle([Bind(Include = "BolumId,BolumAdi")] Bolum bolum)
        {
            if (ModelState.IsValid)
            {
                var bolum1 = db.Bolums.FirstOrDefault(x => x.BolumAdi == bolum.BolumAdi);
                if (bolum1 == null)
                {
                    db.Entry(bolum).State = EntityState.Modified;
                   
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Bu Bölüm mevcut";
                }
                
              
            }
            return View(bolum);
        }

        public string Sil(int id)
        {
            var bolum = db.Bolums.FirstOrDefault(x => x.BolumId == id);
            db.Bolums.Remove(bolum);
            try
            {
                db.SaveChanges();
                return "başarılı";
            }
            catch (Exception e)
            {
                return "hata oluştu";
            }
           


        }
    }
}

StokOtomasyanu/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StokOtomasyanu;

namespace StokOtomasyanu.Controllers
{
    
    public class KullaniciController : Controller
    {
        private StokTakipContext db = new StokTakipContext();

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Index()
        {
            var kullanicilars = db.Kullanicilars.Include(k => k.Bolum).Include(k => k.Roller);
            return View(kullanicilars.ToList());
        }

        public ActionResult Ara(string q)
        {
            var kullanicilars = db.Kullanicilars.Include(k => k.Bolum).Include(k => k.Roller);
            if (string.IsNullOrEmpty(q)==false)
            {
                kullanicilars = db.Kullanicilars.Where(i => i.KullaniciAdi.Contains(q));
            }

            return View(kullanicilars.ToList());

        }



        [Authorize(Roles = "Admin")]
        public ActionResult Yeni()
        {
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi");
            ViewBag.RoleId = new SelectList(db.Rollers, "RoleId", "RolAdi");
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni([Bind(Include = "KullaniciId,KullaniciAdi,Sifre,RoleId,BolumId,Ad,Soyad")] Kullanicilar kullanicilar)
        {

            if (ModelState.IsValid)
            {
                var kullanici = db.Kullanicilars.FirstOrDefault(x => x.KullaniciAdi == kullanicilar.KullaniciAdi);
                if (kullanici == null)
                {
                    db.Kullanicilars.Add(kullanicilar);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Kullanıcı Adı bulunmaktadır.";
                }

            }

            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", kullanicilar.BolumId);
            ViewBag.RoleId = new SelectList(db.Rollers, "RoleId", "RolAdi", kullanicilar.RoleId);
            return View(kullanicilar);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanicilar kullanicilar = db.Kullanicilars.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", kullanicilar.BolumId);
            ViewBag.RoleId = new SelectList(db.Rollers, "RoleId", "RolAdi", kullanicilar.RoleId);

            var bk = db.Kullanicilars.FirstOrDefault(i => i.KullaniciAdi == "deneme");

            ViewBag.Konumx = bk.Ad;
            ViewBag.Konumy = bk.Soyad;

            return View(kullanicilar);
        }

        public ActionResult AlinanUrunler()
        {
            var alinanurunler = db.TblUrunAl.
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Duzenle([Bind(Include = "KullaniciId,KullaniciAdi,Sifre,RoleId,BolumId,Ad,Soyad")] Kullanicilar kullanicilar)
        {
            if (ModelState.IsValid)
            {
                var kullanici = db.Kullanicilars.FirstOrDefault(x => x.KullaniciAdi == kullanicilar.KullaniciAdi);
                if (kullanici == null)
                {
                    db.Entry(kullanicilar).State = EntityState.Modified;
                    
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Kullanıcı Adı bulunmaktadır.";
                }

                
            }
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", kullanicilar.BolumId);
            ViewBag.RoleId = new SelectList(db.Rollers, "RoleId", "RolAdi", kullanicilar.RoleId);
            return View(kullanicilar);
        }





        [HttpPost]
        [Authorize(Roles = "Admin")]
        public string Sil(int id)
        {
           

            Kullanicilar kullanicilar = db.Kullanicilars.FirstOrDefault(x => x.KullaniciId == id);
            db.Kullanicilars.Remove(kullanicilar);

            db.SaveChanges();
            return "başarılı";




        }
    }
}

StokOtomasyanu/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using StokOtomasyanu;

namespace StokOtomasyanu.Controllers
{

    public  class UrunController : Controller
    {
        private StokTakipContext db = new StokTakipContext();



        public ActionResult Index()
        {
           
            var urunlers = db.Urunlers.Include(u => u.Bolum).Include(u => u.Kategoriler).Include(u => u.Tedarikci);
           
              
                return View(urunlers.ToList());
            
            
        }

        public ActionResult Ara(string q)
        {
            var urunlers = db.Urunlers.Include(u => u.Bolum).Include(u => u.Kategoriler).Include(u => u.Tedarikci);
          
                urunlers = urunlers.Where(x => x.UrunaAdi.Contains(q));
                
            
            return View(urunlers.ToList());
        }



        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni()
        {
            ViewBag.BolumID = new SelectList(db.Bolums, "BolumId", "BolumAdi");
            ViewBag.KategoriId = new SelectList(db.Kategorilers, "KategoriId", "KategoriAdi");
            ViewBag.TedarikciId = new SelectList(db.Tedarikcis, "TedarikciId", "TedarikciAdi");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni([Bind(Include = "UrunId,KategoriId,TedarikciId,UrunaAdi,UrunBirimFiyati,SatinAlinmaTarihi,Stok,StokDurum,BolumID")] Urunler urunler)
        {
            if (ModelState.IsValid)
            {
                var urun = db.Urunlers.FirstOrDefault(x => x.UrunaAdi == urunler.UrunaAdi);
                if (urun == null)
                {
                    db.Urunlers.Add(urunler);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Ürün Bulunmaktadır.";
                }

            }

            

            ViewBag.BolumID = new SelectList(db.Bolums, "BolumId", "BolumAdi", urunler.BolumID);
            ViewBag.KategoriId = new SelectList(db.Kategorilers, "KategoriId", "KategoriAdi", urunler.KategoriId);
            ViewBag.TedarikciId = new SelectList(db.Tedarikcis, "TedarikciId", "TedarikciAdi", urunler.TedarikciId);
            return View(urunler);
        }

        // GET: Urun/Edit/5
        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Duzenle(int? id)
        {
           
            Urunler urunler = db.Urunlers.Find(id);
            if (urunler.UrunId <= 0)
            {
                return RedirectToAction("Index");
            }


            if (urunler == null)
            {
                return HttpNotFound();
            }
            ViewBag.BolumID = new SelectList(db.Bolums, "BolumId", "BolumAdi", urunler.BolumID);
            ViewBag.KategoriId = new SelectList(db.Kategorilers, "KategoriId", "KategoriAdi", urunler.KategoriId);
            ViewBag.TedarikciId = new SelectList(db.Tedarikcis, "TedarikciId", "TedarikciAdi", urunler.TedarikciId);
            return View(urunler);

            

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Duzenle([Bind(Include = "UrunId,KategoriId,TedarikciId,UrunaAdi,UrunBirimFiyati,SatinAlinmaTarihi,Stok,StokDurum,BolumID")] Urunler urunler)
        {
          

            if (ModelState.IsValid)
            {

                var urun2 = db.Urunlers.FirstOrDefault(x => x.UrunaAdi == urunler.UrunaAdi);
            if (urun2 == null)
            {
                db.Entry(urunler).State = EntityState.Modified;
                db.SaveChanges();
                    return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Yanlis = "Ürün bulunmaktadır.";
            }



            
                
                
            }
            ViewBag.BolumID = new SelectList(db.Bolums, "BolumId", "BolumAdi", urunler.BolumID);
            ViewBag.KategoriId = new SelectList(db.Kategorilers, "KategoriId", "KategoriAdi", urunler.KategoriId);
            ViewBag.TedarikciId = new SelectList(db.Tedarikcis, "TedarikciId", "TedarikciAdi", urunler.TedarikciId);
            return View(urunler);
        }




        [Authorize(Roles = "Admin ,Satın Alma Şefi")]


        [HttpPost]
        public string Sil(int id)
        {
        StokTakipContext dba = new StokTakipContext();
        Urunler urunler = dba.Urunlers.FirstOrDefault(x => x.UrunId == id);
            dba.Urunlers.Remove(urunler);
            try
            {
                dba.SaveChanges();
                return "başarılı";
            }
            catch (Exception e)
            {
                return "hata";
            }


        }

       

    }
}

StokOtomasyanu/Views/Shared/Search.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<style type="text/css">
    .form-control-borderless {
        border: none;
    }

    .form-control-borderless:hover, .form-control-borderless:active, .form-control-borderless:focus {
        border: none;
        outline: none;
        box-shadow: none;
    }
</style>
@using (Html.BeginForm("Index","Urun",FormMethod.Get))
{

    <div class="container">
        <br/>
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <form class="card card-sm">
                    <div class="card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <!--end of col-->
                        <div class="col">
                            @Html.TextBox("Aranacak Kelime",null,htmlAttributes:new {@class="form-control form-control-lg form-control - borderless"})

                        </div>
                        <!--end of col-->
                        <div class="col-auto">
                            <button class="btn btn-lg btn-success" type="submit">Search</button>
                        </div>
                        <!--end of col-->
                    </div>
                </form>
            </div>
            <!--end of col-->
        </div>
    </div>
}

StokOtomasyanu/Views/Shared/_Layout.cshtml
@using System.Drawing
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stok Takip Otomasyonu</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ürünler", "Index", "Urun", new { area = "" }, new { @class = "navbar-brand" })
                @if (User.IsInRole("Admin") || User.IsInRole("Satın Alma Şefi"))
                {
                    @Html.ActionLink("Kullanıcı", "Index", "Kullanici", new { area = "" }, new { @class = "navbar-brand" })
                }

                @Html.ActionLink("Atıklar", "Index", "Atik", new { area = "" }, new { @class = "navbar-brand" })
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Tedarikçi", "Index", "Tedarikci", new { area = "" }, new { @class = "navbar-brand" })
                }
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Kategori", "Index", "Kategori", new { area = "" }, new { @class = "navbar-brand" })
                }
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Bölüm", "Index", "Bolum", new { area = "" }, new { @class = "navbar-brand" })
                }


                @Html.ActionLink("Kişi Zimmet", "Index", "KisiZimmet", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Bölüm Zimmet", "Index", "BolumZimmet", new { area = "" }, new { @class = "navbar-brand" }) |
                <p class="navbar-brand">Hoş Geldiniz @HttpContext.Current.User.Identity.Name</p>

                <a href="/Security/LogOut" class="navbar-brand text-danger">Çıkış</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>

        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Stok Takip</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>