StokOtomasyanu/Controllers/BolumZimmetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using StokOtomasyanu;

namespace StokOtomasyanu.Controllers
{
    public class BolumZimmetController : Controller
    {
        private StokTakipContext db = new StokTakipContext();

       
        public ActionResult Index()
        {

            var bolumZimmets = db.BolumZimmets.Include(b => b.Bolum).Include(b => b.Urunler);
           
            return View(bolumZimmets.ToList());
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Yeni()
        {
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi");
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi");
            return View();
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni([Bind(Include = "BolumZimmetId,BolumId,UrunId,Durum")] BolumZimmet bolumZimmet)
        {
            if (ModelState.IsValid)
            {
                var bolumzimmet1 = db.BolumZimmets.FirstOrDefault(x =>
                    x.BolumId == bolumZimmet.BolumId && x.UrunId == bolumZimmet.UrunId);
                if (bolumzimmet1==null)
                {
                    db.BolumZimmets.Add(bolumZimmet);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Yanlis = "Aynı ürün Bir daha zimmetlenemez.";

                }
            }

            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", bolumZimmet.BolumId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", bolumZimmet.UrunId);
            return View(bolumZimmet);
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        public ActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BolumZimmet bolumZimmet = db.BolumZimmets.Find(id);
            if (bolumZimmet == null)
            {
                return HttpNotFound();
            }
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", bolumZimmet.BolumId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", bolumZimmet.UrunId);
            return View(bolumZimmet);
        }

        [Authorize(Roles = "Admin,Satın Alma Şefi")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle([Bind(Include = "BolumZimmetId,BolumId,UrunId,Durum")] BolumZimmet bolumZimmet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bolumZimmet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BolumId = new SelectList(db.Bolums, "BolumId", "BolumAdi", bolumZimmet.BolumId);
            ViewBag.UrunId = new SelectList(db.Urunlers, "UrunId", "UrunaAdi", bolumZimmet.UrunId);
            return View(bolumZimmet);
        }

        public string Sil(int id)
        {
            BolumZimmet bolumZimmet = db.BolumZimmets.FirstOrDefault(x => x.BolumZimmetId == id);
            db.BolumZimmets.Remove(bolumZimmet);
            try
            {
                db.SaveChanges();
                return "Silindi";
            }
            catch (Exception e)
            {
                return "Hata";
            }
            
        }
        [HttpPost]
        [ValidateInput(false)]
        public FileResult Pdf(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 50f, 10f, 50f, 20f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "BolumZimmetRapor.pdf");
            }
        }

       
    }
}

StokOtomasyanu/Views/BolumZimmet/Duzenle.cshtml
@model StokOtomasyanu.BolumZimmet

@{
    ViewBag.Title = "Düzenle";
}

<h2>Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Bölüm Zimmet</h4>
    <hr />
    <p class="text-danger"> @ViewBag.Yanlis</p>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.BolumZimmetId)

    <div class="form-group">
        @Html.LabelFor(model => model.BolumId, "BolumId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BolumId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BolumId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunId, "UrunId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UrunId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UrunId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

StokOtomasyanu/Views/BolumZimmet/Index.cshtml
@model IEnumerable<StokOtomasyanu.BolumZimmet>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
@if (User.IsInRole("Admin") || User.IsInRole("Satın Alma Şefi"))
{
    @Html.ActionLink("Yeni Ekle", "Yeni", "", htmlAttributes: new {@class = "btn btn-success"})
}
</p>
<div id="Grid">
<table class="table">
    <tr>
        <th>
            Durum
        </th>
        <th>
            Bölüm Adı
        </th>
        <th>
            Ürün Adı
        </th>
       <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @if (item.Durum == true)
                {
                    @Html.Label("Aktif")
                }
                else
                {
                    @Html.Label("Pasif")
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bolum.BolumAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Urunler.UrunaAdi)
            </td>
            <td>
            @if (User.IsInRole("Admin") || User.IsInRole("Satın Alma Şefi"))
            {
                @Html.ActionLink("Düzenle", "Duzenle", new {id = item.BolumZimmetId}, htmlAttributes: new {@class = "btn btn-warning"})

                <a href="#" class="btn btn-danger bolzimmetsil" data-bolzimetid="@item.BolumZimmetId">Sil</a>
            }
            </td>
        </tr>
    }

</table>
</div>
@using (Html.BeginForm("Pdf", "BolumZimmet", FormMethod.Post))
{
    <input type="hidden" name="GridHtml"/>
    <input class="btn btn-default" type="submit" id="btnSubmit" value="Rapor"/>
}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml']").val($("#Grid").html());
        });
    });
</script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>

    $(".bolzimmetsil").click(function () {
        var sonuc=confirm("Kayıt Silinsin mi?");
        if (sonuc) {
            var bolzimetid = $(this).data("bolzimetid");
            $.ajax({
                type: "POST",
                url: "/BolumZimmet/Sil/" + bolzimetid,
                success: function(parameters) {
                    alert("Kayıt Silindi");
                    window.location.replace("/BolumZimmet/Index");
                },
                error: function() {
                    alert("kayıt silme sırasında hata oluştu");
                }



            });

        } else {
            alert("iptal edildi");

        }

    });
</script>

StokOtomasyanu/Views/BolumZimmet/Yeni.cshtml
@model StokOtomasyanu.BolumZimmet

@{
    ViewBag.Title = "Yeni";
}

<h2>Yeni</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Bölüm Zimmet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p class="text-danger"> @ViewBag.Yanlis</p>
    <div class="form-group">
        @Html.LabelFor(model => model.BolumId, "Bölüm Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BolumId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BolumId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunId, "Ürün Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UrunId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UrunId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-sucess" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>